### ISSUE TITLE
Service definition not registered

### ISSUE THREAD

**Issue by lionelbzv** [propelorm/PropelAclBundle#2]
It seems this bundle doesn't register the required `propel.security.acl.provider` service used in `security.yml`: I had to put this definition in my project's `services.yml` to make it work.

```
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                              
  Unable to replace alias "security.acl.provider" with actual definition "propel.security.acl.provider".  

  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The service definition "propel.security.acl.provider" does not exist.       
```

**Comment by havvg** [comment]
Thanks. I didn't have setup a complete test environment from scratch. That's why it's not released yet. I will fix it this evening!

**Comment by havvg** [comment]
The `PropelAclExtension` has been added.
